### PR TITLE
Artemis 1590 Fixes

### PR DESCRIPTION
**Pull request by franz1981**

### CODE REVIEW

**Comment by franz1981** [comment]
@jmesnil Right now it missed the table name force case bejaviours of the original version of @mtaylor:
- DERBY -> upperCase
- MySQL -> lowerCase
- Postgres -> lowerCase

I will ask @mtaylor if it is mandatory or not

**Comment by mtaylor** [comment]
@franz1981 Yes these are required.

**Comment by franz1981** [comment]
@mtaylor Great, thanks! I've added the few bits to support it via properties

**Comment by jmesnil** [comment]
@franz1981 thanks for looking at it and fixing the case sensitivity of the table names.

I was not sure if that was required or not as the original code is not consistent with it.
E.g. DerbySQLProvider use `tableName.toUpperCase()` when calling its super constructor but uses directly `tableName` in its specific `createFileTableSQL` (see https://github.com/apache/activemq-artemis/blob/f331a3f6598a580a7741c88cf3047b45da4dfa59/artemis-jdbc-store/src/main/java/org/apache/activemq/artemis/jdbc/store/drivers/derby/DerbySQLProvider.java#L30-L34)

With your patch, the behaviour will be consistent.

**Comment by franz1981** [comment]
@jmesnil Don't worry, I hope the fixes will match your expectations on how the PR has to do :+1:

**Comment by franz1981** [comment]
@jmesnil How it seems? It can be merged as it is?
I'm trying to perform some tests on DB2 but the office (in UK for my region) to obtain the IBM-ID and download the driver is already closed :O

**Pull request merged**
